const sendingstaffdata = {
  alternateNumber: '',
  bankDetails: {
    accountNumber: 'Ejej',
    bankName: 'Ejej',
    branch: 'Irej',
    holderName: 'Ejej',
    ifscCode: 'Ejej',
  },
  currentAddress: {
    address: 'Snsn',
    dist: 'Dndn',
    pinCode: '123456',
    state: 'Snsn',
  },
  dob: '9/1/2022',
  educationInfo: [
    {
      className: 'string',
      grades: 'string',
      instituteName: 'string',
      marks: 'string',
      passingYear: 'string',
      stream: 'string',
      university: 'string',
    },
  ],
  email: 'ps@gmail.com',
  experiences: [
    {
      designation: 'Jrje',
      document: 'string',
      employerName: 'Jrje',
      from: undefined,
      salary: 'Snsnsn',
      to: undefined,
      worksOn: [Array],
    },
  ],
  fatherInfo: {
    email: 'string',
    firstName: 'Snsn',
    lastName: '',
    middleName: '',
    mobileNumber: 'string',
    occupation: 'string',
  },
  firstName: 'Prakash',
  gender: 'Male',
  lastName: '',
  lastSalary: undefined,
  maritalStatus: 'Married',
  middleName: '',
  mobileNumber: '7015500526',
  motherInfo: {
    email: 'string',
    firstName: 'Snsn',
    lastName: '',
    middleName: '',
    mobileNumber: 'string',
    occupation: 'string',
  },
  pan: 'Zbsb',
  permanentAddress: {
    address: 'Snsn',
    dist: 'Dndn',
    pinCode: '123456',
    state: 'Snsn',
  },
  profilePic: undefined,
  staffDocId: 'string',
};
const dataaaa = {
  alternateNumber: 'string',
  bankDetails: {
    accountNumber: 'Fghj',
    bankName: 'Fhj',
    branch: 'Dgh',
    holderName: 'Cbnn',
    ifscCode: 'Cgjj',
  },
  currentAddress: {
    address: 'Fhff',
    dist: 'Gfc ',
    pinCode: '123456',
    state: 'Cgjj',
  },
  dob: '2022-1-11',
  educationInfo: [
    {
      className: 'string',
      grades: 'string',
      instituteName: 'string',
      marks: 'string',
      passingYear: 'string',
      stream: 'string',
      university: 'string',
    },
  ],
  email: 'ps3@gmail.com',
  experiences: [
    {
      designation: 'Fhj',
      document: 'string',
      employerName: 'Fhh',
      from: '2022-1-4',
      salary: 1875467,
      to: '2022-1-19',
      worksOn: [Array],
    },
  ],
  fatherInfo: {
    email: 'string',
    firstName: 'Fgh',
    lastName: 'string',
    middleName: 'string',
    mobileNumber: 'string',
    occupation: 'string',
  },
  firstName: 'ps',
  gender: 'Male',
  lastName: 'Gadekar',
  lastSalary: '1875467',
  maritalStatus: 'Married',
  middleName: 'Ashok',
  mobileNumber: '7015500529',
  motherInfo: {
    email: 'string',
    firstName: 'Bbbcc',
    lastName: 'string',
    middleName: 'string',
    mobileNumber: 'string',
    occupation: 'string',
  },
  pan: 'Cvhj',
  permanentAddress: {
    address: 'Fhff',
    dist: 'Gfc ',
    pinCode: '123456',
    state: 'Cgjj',
  },
  profilePic:
    'https://ekalprofilepictures.s3.ap-south-1.amazonaws.com/1643291999275-rn_image_picker_lib_temp_b2303a3c-cb06-41c2-8138-534ff0d3b8da.jpg',
  staffDocId: '61f29d95f26d424411f270a2',
};
const baaaaa = {
  alternateNumber: '7015500526',
  bankDetails: {
    accountNumber: 'string',
    bankName: 'string',
    branch: 'string',
    holderName: 'string',
    ifscCode: 'string',
  },
  currentAddress: {
    address: 'string',
    dist: 'string',
    pinCode: 'string',
    state: 'string',
  },
  dob: '2022-01-20T13:11:10.751Z',
  educationInfo: [
    {
      className: 'string',
      grades: 'string',
      instituteName: 'string',
      marks: 'string',
      passingYear: 'string',
      stream: 'string',
      university: 'string',
    },
  ],
  email: 'ps@gmail.com',
  experiences: [
    {
      designation: 'string',
      document: 'string',
      employerName: 'string',
      from: '2022-01-20T13:11:10.751Z',
      salary: 0,
      to: '2022-01-20T13:11:10.751Z',
      worksOn: ['string'],
    },
  ],
  fatherInfo: {
    email: 'string',
    firstName: 'string',
    lastName: 'string',
    middleName: 'string',
    mobileNumber: 'string',
    occupation: 'string',
  },
  firstName: 'string',
  gender: 'string',
  lastName: 'string',
  lastSalary: 'string',
  maritalStatus: 'string',
  middleName: 'string',
  mobileNumber: 'string',
  motherInfo: {
    email: 'string',
    firstName: 'string',
    lastName: 'string',
    middleName: 'string',
    mobileNumber: 'string',
    occupation: 'string',
  },
  pan: 'string',
  permanentAddress: {
    address: 'string',
    dist: 'string',
    pinCode: 'string',
    state: 'string',
  },
  profilePic:
    'https://ekalprofilepictures.s3.ap-south-1.amazonaws.com/1642270853976-School_Logo.jpg',
  staffDocId: '61e280d987be64760310cb18',
};
const staffData = {
  list: [
    {
      alternateNumber: null,
      bankDetails: [Object],
      classTeacherFor: null,
      currentAddress: [Object],
      dob: '2022-01-03T18:30:00.000+00:00',
      educationInfo: [Array],
      email: 'sushil@gmail.com',
      employmentInfo: [Object],
      experiences: [Array],
      fatherInfo: [Object],
      firstName: 'Sushil',
      fullName: 'Sushil  Jaiswal',
      gender: 'Male',
      id: '61e129cec81b5a5c6d7cf24f',
      inchargeOf: null,
      lastName: 'Jaiswal',
      lastSalary: null,
      leaves: [Array],
      maritalStatus: null,
      middleName: '',
      mobileNumber: '9415052494',
      motherInfo: [Object],
      pan: 'ABCDE1323C',
      password: null,
      permanentAddress: [Object],
      profilePic:
        'https://ekalprofilepictures.s3.ap-south-1.amazonaws.com/1642682356231-Cool-Profile-Picture.jpg',
      schoolConfirmed: true,
      schoolDocId: '61e0f9d5fd112a528eff66d3',
      userType: null,
    },
  ],
  message: 'Successful',
};

const data2 = {
  list: [
    {
      activeSession: '2021-2022',
      affiliatedTo: null,
      directorPic:
        'https://ekalprofilepictures.s3.ap-south-1.amazonaws.com/1642270855611-Cool-Profile-Picture.jpg',
      dob: null,
      educationType: null,
      ekalRefNumber: 'string',
      email: 'school@school.com',
      employeeId: 0,
      gender: null,
      id: '61e0f9d5fd112a528eff66d3',
      invoiceNumber: 2,
      medium: [Array],
      schoolAddress: [Object],
      schoolAdmin: [Object],
      schoolCode: 'ABCD',
      schoolContactNumber: '9415052494',
      schoolInitials: 'HPKP',
      schoolLogo:
        'https://ekalprofilepictures.s3.ap-south-1.amazonaws.com/1642270853976-School_Logo.jpg',
      schoolName: 'St. HPKP Central High School',
      schoolRegisterDate: '2022-01-14T03:25:53.777+00:00',
      schoolRegisterNumber: '12345',
      school_p_name: null,
      verified: true,
    },
  ],
  message: 'Success',
};

// in school stafff schoolDocId

const directorData = {
  list: [
    {
      activeSession: '2021-2022',
      affiliatedTo: 'CBSE - Central Board of Secondary Education',
      directorPic:
        'https://ekalprofilepictures.s3.ap-south-1.amazonaws.com/1642270855611-Cool-Profile-Picture.jpg',
      dob: '1970-01-22T18:30:00.000+00:00',
      educationType: null,
      ekalRefNumber: 'string',
      email: 'school@school.com',
      employeeId: 1,
      gender: null,
      id: '61e0f9d5fd112a528eff66d3',
      invoiceNumber: 2,
      medium: [Array],
      schoolAddress: [Object],
      schoolAdmin: [Object],
      schoolCode: 'ABCD',
      schoolContactNumber: '9415052494',
      schoolInitials: 'HPKP',
      schoolLogo:
        'https://ekalprofilepictures.s3.ap-south-1.amazonaws.com/1642270853976-School_Logo.jpg',
      schoolName: 'St. HPKP Central High School',
      schoolRegisterDate: '2022-01-14T03:25:53.777+00:00',
      schoolRegisterNumber: '12345',
      school_p_name: null,
      verified: true,
    },
  ],
  message: 'Success',
};
