export const NavigationString = {
  // update Profile screen names
  OkStaff: 'OkStaff',
  StaffStack: 'StaffStack',
  DirectorStack: 'DirectorStack',
  PersonalDetail: 'PersonalDetail',
  BankDetail: 'BankDetail',
  ParenDetail: 'ParenDetail',
  ExperienceDetail: 'ExperienceDetail',
  AddressDetail: 'AddressDetail',
  RequestSchool: 'RequestSchool',
  RequestSchool2: 'RequestSchool2',

  // Auth Screen names
  Login: 'AuthHome',
  Signup: 'Signup',
  Forgot: 'Forgot',
  Home: 'Home',

  Message: 'Message',
  Events: 'Events & Calender',
  Academics: 'Academics',
  Dashboard: 'Dashboard',
  MainStack: 'MainStack',
  TimeTable: 'Time Table',
  Examination: 'Examination',
  EventsCalenders: 'Events & Calenders',
  Syllabus: 'Syllabus',
  LeaveApllication: 'Leave Apllication',
  Library: 'Library',
  Transport: 'Transport',
  AssignedTeacher: 'Assigned Teacher',
  NoticeBoard: 'Notice Board',
  Result: 'Result',
  Hostel: 'Hostel',
  VisitorControl: 'Visitor Control',
  Complains: 'Complains',
  QuestionPaper: 'Question Paper',
  Results: 'Results',
  Exams: 'Exams',
  Expenses: 'Expenses',
  Fees: 'Fess',
  Collection: 'CollectionStack',
  ReceptionDashboard: 'ReceptionDashboard',
  LedgerDashboard: 'LedgerDashboard',
  DashboardStack: 'DashboardStack',
  ExamStack: 'ExamStack',
  LedgerStack: 'LedgerStack',
  ReceptionStack: 'ReceptionStack',
  CollectionStack: 'CollectionStack',
  ExpensesStack: 'ExpensesStack',
  FeesStack: 'FessStack',

  // inventory screen name constant
  InventoryDashboard: 'Inventory',
  inventoryMainStack: 'inventoryMainStack',
  AddItemStack: 'Add Item',
  AddItemStockStack: 'Add Item Stock',
  IssueItemStack: 'Issue Item',
  ItemCategoryStack: 'Item Category',
  ItemStoreStack: 'Item Store',
  ItemSupplierStack: 'Item Supplier',
  AddItemScreen: 'AddItem',
  AddItemStockScreen: 'AddItemStock',
  IssueItemScreen: 'IssueItem',
  ItemCategoryScreen: 'ItemCategory',
  ItemStoreScreen: 'ItemStore',
  ItemSupplierScreen: 'ItemSupplier',

  // Homework screen constant
  Assignments: 'Assignment',
  AssignmentsStack: 'AssignmentsStack',
  HomeworkDashboard: 'Homework',
  Homeworkselect: 'Homeworkselect',
  CreateHomework: 'CreateHomework',
  PostedSelect: 'PostedSelect',
  PostedHomework: 'PostedHomework',
  createHomework: 'createHomework',
  Homework: 'Homework',

  // Attendace Screen names
  ViewAttendanceByDate: 'View Attendance',
  Attendance: 'Attendance',
  StaffAttendance: 'Staff Attendance',
  AttendanceStack: 'AttendanceStack',
  Attendace: 'Attendance',
  DetailAttendance: 'Detail Attendace',
  ViewAttendance: 'View Attendance By Date',
  AdmissionEnquiry: 'StaffAttendance',
};
